# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ys-26xi8xZWJoA1CBFQP3g-NgkIgmI0h
"""

import streamlit as st
from ultralytics import YOLO
from PIL import Image
import numpy as np
import cv2

# Load your trained YOLO model
model_path = "/content/gdrive/MyDrive/PotholeDetection/runs/detect/train5/weights/best.pt"
model = YOLO(model_path)

st.title("Pothole Detection Web App")

uploaded_file = st.file_uploader("Upload an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Read the image
    image = Image.open(uploaded_file)
    img_array = np.array(image)

    # Convert to BGR for OpenCV
    img_bgr = cv2.cvtColor(img_array, cv2.COLOR_RGB2BGR)

    # Perform inference
    results = model(img_bgr, conf=0.4)

    # Get the first result
    result = results[0]

    # Draw boxes and labels
    annotated_img = result.plot()

    # Convert back to RGB for Streamlit
    annotated_img_rgb = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB)

    st.image(annotated_img_rgb, caption="Detected Potholes", use_column_width=True)

    # Optionally display detection details
    st.subheader("Detection Details:")
    for box in result.boxes:
        x1, y1, x2, y2 = [int(coord) for coord in box.xyxy[0]]
        conf = box.conf[0]
        cls = int(box.cls[0])
        label = model.names[cls]
        st.write(f"Object: {label}, Confidence: {conf:.2f}, Bounding Box: ({x1}, {y1}, {x2}, {y2})")